platform :ios, '10.0'

target 'Flash Chat iOS13' do
  use_frameworks!

#pod 'CLTypingLabel', '~> 0.4.0'

# Add the Firebase pod for Google Analytics
#pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

end
